name: ðŸ› Bug Report
description: Something is wrong with msw-server-helper.
body:
  - type: markdown
    attributes:
      value: >-
        Thank you for helping to improve @gregcello/msw-server-helper!

        This is a side project, and so response times may be slow. To
        help with reporting any issues, please provide the following details:

        - msw version (ex: 0.49.2)
        - @gregcello/msw-server-helper version
        - @gregcello/msw-server-helper-cypress version (if used)
        - cypress version (if used)

        if possible, provide a paste of the error in 3 backticks:

        ```
        error here
        ```

        and/or a screenshot/screencast (command-shift-5 on a Mac to generate these)

  - type: input
    attributes:
      label: Have you experienced this bug with the latest version of the template?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
