blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/cellog/msw-server-helper/discussions/categories/q-a
    about:
      If you can't get something to work the way you expect, open a question in
      the msw-server-helper discussions.
  - name: Feature Request
    url: https://github.com/cellog/msw-server-helper/discussions/categories/ideas
    about:
      We appreciate you taking the time to improve msw-server-helper with your ideas, but we
      use the msw-server-helper Discussions for this instead of the issues tab.
